apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: r4p3w4fzd-python-prod
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/r4p3w4fzd-python/overlays/prod
    repoURL: https://github.com/rhtap-rhdh-qe/r4p3w4fzd-python-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: tssc-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
